### ISSUE TITLE
Default journal

### ISSUE THREAD

**Issue by steinbrueckri** [ishchow/deardiary#5]
How can I define a default journal to pick?

**Comment by ishchow** [comment]
There isn't really a concept of default journal in this plugin. It will always ask you which journal to pick.

As a workaround, you could put your default journal as the first element in config.journals and then call this [function](https://github.com/ishchow/nvim-deardiary/blob/e25a5ddd1ed0326937bc4f385a6963f92de92ceb/lua/deardiary/init.lua#L78) with index 0 on startup as a workaround.
